# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  GLFW_config = debug
  GLAD_config = debug
  IMGUI_config = debug
  freetype_config = debug
  msdfgen_config = debug
  MSDF_ATLAS_GEN_config = debug
  Banana_config = debug
  Sandbox_config = debug

else ifeq ($(config),release)
  GLFW_config = release
  GLAD_config = release
  IMGUI_config = release
  freetype_config = release
  msdfgen_config = release
  MSDF_ATLAS_GEN_config = release
  Banana_config = release
  Sandbox_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := GLFW GLAD IMGUI freetype msdfgen MSDF-ATLAS-GEN Banana Sandbox

.PHONY: all clean help $(PROJECTS) dependencies engine game

all: $(PROJECTS)

dependencies: GLAD GLFW IMGUI MSDF-ATLAS-GEN freetype msdfgen

engine: Banana

game: Sandbox

GLFW:
ifneq (,$(GLFW_config))
	@echo "==== Building GLFW ($(GLFW_config)) ===="
	@${MAKE} --no-print-directory -C Banana/vendor/GLFW -f Makefile config=$(GLFW_config)
endif

GLAD:
ifneq (,$(GLAD_config))
	@echo "==== Building GLAD ($(GLAD_config)) ===="
	@${MAKE} --no-print-directory -C Banana/vendor/GLAD -f Makefile config=$(GLAD_config)
endif

IMGUI:
ifneq (,$(IMGUI_config))
	@echo "==== Building IMGUI ($(IMGUI_config)) ===="
	@${MAKE} --no-print-directory -C Banana/vendor/IMGUI -f Makefile config=$(IMGUI_config)
endif

freetype:
ifneq (,$(freetype_config))
	@echo "==== Building freetype ($(freetype_config)) ===="
	@${MAKE} --no-print-directory -C Banana/vendor/MSDF-ATLAS-GEN/msdfgen/freetype -f Makefile config=$(freetype_config)
endif

msdfgen: freetype
ifneq (,$(msdfgen_config))
	@echo "==== Building msdfgen ($(msdfgen_config)) ===="
	@${MAKE} --no-print-directory -C Banana/vendor/MSDF-ATLAS-GEN/msdfgen -f Makefile config=$(msdfgen_config)
endif

MSDF-ATLAS-GEN: freetype msdfgen
ifneq (,$(MSDF_ATLAS_GEN_config))
	@echo "==== Building MSDF-ATLAS-GEN ($(MSDF_ATLAS_GEN_config)) ===="
	@${MAKE} --no-print-directory -C Banana/vendor/MSDF-ATLAS-GEN -f Makefile config=$(MSDF_ATLAS_GEN_config)
endif

Banana:
ifneq (,$(Banana_config))
	@echo "==== Building Banana ($(Banana_config)) ===="
	@${MAKE} --no-print-directory -C Banana -f Makefile config=$(Banana_config)
endif

Sandbox: Banana GLAD IMGUI GLFW MSDF-ATLAS-GEN msdfgen freetype
ifneq (,$(Sandbox_config))
	@echo "==== Building Sandbox ($(Sandbox_config)) ===="
	@${MAKE} --no-print-directory -C Sandbox -f Makefile config=$(Sandbox_config)
endif

clean:
	@${MAKE} --no-print-directory -C Banana/vendor/GLFW -f Makefile clean
	@${MAKE} --no-print-directory -C Banana/vendor/GLAD -f Makefile clean
	@${MAKE} --no-print-directory -C Banana/vendor/IMGUI -f Makefile clean
	@${MAKE} --no-print-directory -C Banana/vendor/MSDF-ATLAS-GEN/msdfgen/freetype -f Makefile clean
	@${MAKE} --no-print-directory -C Banana/vendor/MSDF-ATLAS-GEN/msdfgen -f Makefile clean
	@${MAKE} --no-print-directory -C Banana/vendor/MSDF-ATLAS-GEN -f Makefile clean
	@${MAKE} --no-print-directory -C Banana -f Makefile clean
	@${MAKE} --no-print-directory -C Sandbox -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   GLFW"
	@echo "   GLAD"
	@echo "   IMGUI"
	@echo "   freetype"
	@echo "   msdfgen"
	@echo "   MSDF-ATLAS-GEN"
	@echo "   Banana"
	@echo "   Sandbox"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"